name: Release

on:
  push:
    #tags:
    #    - 'v*'

jobs:
  release:
    name: Build release artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.19.0'
    - name: Build for arch
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: go build
    - name: Stash
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.os }}-${{ matrix.arch }}
        path: ./doggo
